### ISSUE TITLE
Add an archive of historical notices

### ISSUE THREAD

**Issue by blaufuss** [nasa-gcn/gcn-schema#213] opened 2024-10-29 20:57 UTC
# Description
There is no publicly visible archive of sent notices available in GCN.  This is an extremely useful feature in two places:
* ensuring recent GCN notices sent went out properly
* providing a historical archive for later use when trying to generate a paper/catalog/presentation about what happened/when after the fact.  

In IceCube, we have our own copy saved of sent notices for our LVK response (https://roc.icecube.wisc.edu/public/LvkNuTrackSearch/) with a copy of we thought we sent, but it is not guaranteed to be tied to
what others received by GCN.  A common historical record we can all point to would be preferred.  

Even as a stop-gap solution, just a “recent history” page that’s a list of the notices posted in the last few days would be helpful, both for being able to ensure things went out correctly , and for debugging new listeners/senders.

# Acceptance criteria

**Comment by lpsinger** [comment] 2024-10-30 01:13
Duplicate of https://github.com/nasa-gcn/gcn.nasa.gov/issues/922.

**Closed by lpsinger** 2024-10-30 01:13 UTC
Labels: enhancement
